# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'defect.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtWidgets, uic, QtGui, QtCore
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtChart import *
'''from PyQt5.QtChart import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *'''

class Ui_DefectAnalytics(object):
    def setupUi(self, DefectAnalytics):
        DefectAnalytics.setObjectName("DefectAnalytics")
        DefectAnalytics.resize(1307, 940)
        DefectAnalytics.setStyleSheet("background-color: rgb(60, 60, 60);")
        self.gridLayout_16 = QtWidgets.QGridLayout(DefectAnalytics)
        self.gridLayout_16.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_16.setSpacing(0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.frame = QtWidgets.QFrame(DefectAnalytics)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("color: rgb(181, 181, 181);")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_15.setContentsMargins(2, 0, 2, 2)
        self.gridLayout_15.setVerticalSpacing(2)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(500, 250))
        self.frame_4.setMaximumSize(QtCore.QSize(500, 250))
        self.frame_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_4.setContentsMargins(-1, 0, -1, 9)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame_4)
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setLineWidth(2)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Line1_2 = QtWidgets.QLabel(self.frame_2)
        self.Line1_2.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Line1_2.setFont(font)
        self.Line1_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.Line1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Line1_2.setObjectName("Line1_2")
        self.gridLayout_2.addWidget(self.Line1_2, 0, 0, 1, 1)
        self.liveLine2 = QtWidgets.QLabel(self.frame_2)
        self.liveLine2.setMinimumSize(QtCore.QSize(0, 225))
        self.liveLine2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.liveLine2.setStyleSheet("background-color: rgb(168, 168, 168);")
        self.liveLine2.setText("")
        self.liveLine2.setObjectName("liveLine2")
        self.gridLayout_2.addWidget(self.liveLine2, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.liveLine1 = QtWidgets.QLabel(self.frame_2)
        self.liveLine1.setMinimumSize(QtCore.QSize(0, 225))
        self.liveLine1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.liveLine1.setStyleSheet("background-color: rgb(168, 168, 168);")
        self.liveLine1.setText("")
        self.liveLine1.setObjectName("liveLine1")
        self.gridLayout.addWidget(self.liveLine1, 1, 0, 1, 1)
        self.Line1 = QtWidgets.QLabel(self.frame_2)
        self.Line1.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Line1.setFont(font)
        self.Line1.setStyleSheet("color: rgb(0, 0, 0);")
        self.Line1.setAlignment(QtCore.Qt.AlignCenter)
        self.Line1.setObjectName("Line1")
        self.gridLayout.addWidget(self.Line1, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 1, 0, 1, 1)
        self.gridLayout_15.addWidget(self.frame_4, 2, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setContentsMargins(0,0,0,0)
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setLineWidth(2)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_17.addWidget(self.label_4, 0, 0, 1, 1)

        self.graphFrame = QtWidgets.QFrame()#self.frame_11)
        self.graphFrame.setMinimumSize(QtCore.QSize(1000, 230))
        self.graphFrame.setMaximumSize(QtCore.QSize(1000, 230))
        self.graphFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.graphFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.graphFrame.setLineWidth(1)
        self.graphFrame.setStyleSheet("background-color: rgb(255, 255, 255);color:rgb(0,0,0)")
        #self.chartFrame.setObjectName("chartFrame")

        self.gridLayout_14 = QtWidgets.QGridLayout(self.graphFrame)
        #self.gridLayout_14.setStyleSheet("background-color: rgb(255, 255, 255);color:rgb(0,0,0)")
        self.gridLayout_14.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_14.setSpacing(0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        #self.defects = QtWidgets.QLabel(self.frame_8)
        self.defects = QtWidgets.QLabel()
        #self.defects = QtWidgets.QPushButton(self.frame)
        self.defects.setMinimumSize(QtCore.QSize(30, 30))
        self.defects.setMaximumSize(QtCore.QSize(30, 30))
        self.defects.setText("")

        self.defects.setStyleSheet("color: rgb(255, 255, 255);")
        defetsimg = QtGui.QPixmap("res/defects.png")
        self.defects.setPixmap(defetsimg)        
        self.defects.setMinimumSize(QtCore.QSize(32, 75))
        self.defects.setMaximumSize(QtCore.QSize(32, 75))
       
        self.defects.setObjectName("defects")
        self.gridLayout_14.addWidget(self.defects, 0, 0, 1, 1)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setSpacing(0)
        
        
        #self.frame_11.setObjectName("frame_11")
        #self.gridLayout_11 = QtWidgets.QGridLayout()#
        #self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        #self.gridLayout_11.setSpacing(0)
        #self.gridLayout_11.setObjectName("gridLayout_11")
        self.chartFrame = QtWidgets.QFrame()#self.frame_11)
        self.chartFrame.setMinimumSize(QtCore.QSize(180, 200))
        self.chartFrame.setMaximumSize(QtCore.QSize(180, 200))
        self.chartFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.chartFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        #self.chartFrame.setLineWidth(1)
        self.chartFrame.setStyleSheet("background-color: rgb(255, 255, 255);color:rgb(255,255,255)")
        self.chartFrame.setObjectName("chartFrame")
        #self.gridLayout_11.addWidget(self.chartFrame, 0, 0, 1, 1)

        self.gridLayout_14.addWidget(self.chartFrame, 0, 2, 1, 1)
        self.plotWidget = QtWidgets.QFrame()
        self.plotWidget.setMinimumSize(QtCore.QSize(600, 200))
        self.plotWidget.setMaximumSize(QtCore.QSize(600, 200))
        self.plotWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.plotWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.plotWidget.setContentsMargins(0,0,0,0)
        self.plotWidget.setLineWidth(1)
        self.plotWidget.setStyleSheet("background-color: rgb(255, 255, 255);color:rgb(255,255,255)")
        
        self.plotWidget.setObjectName("plotWidget")       


        self.gridLayout_14.addWidget(self.plotWidget, 0, 1, 1, 1)  



        self.gridLayout_17.addWidget(self.graphFrame, 1, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frame_8, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.frame_7, 2, 1, 2, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.defectTableWidget = QtWidgets.QTableWidget(self.frame_8)
        self.defectTableWidget.setStyleSheet("color: rgb(0, 0, 0);")
        self.defectTableWidget.setObjectName("defectTableWidget")
        self.defectTableWidget.setColumnCount(5)
        self.defectTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.defectTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.defectTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.defectTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.defectTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.defectTableWidget.setHorizontalHeaderItem(4, item)
        self.verticalLayout_2.addWidget(self.defectTableWidget)
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_9.setStyleSheet("background-color: rgb(154, 154, 154);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_12.setContentsMargins(-1, 1, -1, 1)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.lineEditDefectName = QtWidgets.QLineEdit(self.frame_9)
        self.lineEditDefectName.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEditDefectName.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEditDefectName.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditDefectName.setObjectName("lineEditDefectName")
        self.gridLayout_12.addWidget(self.lineEditDefectName, 0, 0, 1, 1)
        self.btnSearch = QtWidgets.QPushButton(self.frame_9)
        self.btnSearch.setMinimumSize(QtCore.QSize(0, 30))
        self.btnSearch.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btnSearch.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/res/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSearch.setIcon(icon)
        self.btnSearch.setIconSize(QtCore.QSize(100, 30))
        self.btnSearch.setFlat(True)
        self.btnSearch.setObjectName("btnSearch")
        self.gridLayout_12.addWidget(self.btnSearch, 0, 1, 1, 1)
        self.btnReset = QtWidgets.QPushButton(self.frame_9)
        self.btnReset.setMinimumSize(QtCore.QSize(0, 30))
        self.btnReset.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btnReset.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/res/reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnReset.setIcon(icon1)
        self.btnReset.setIconSize(QtCore.QSize(100, 30))
        self.btnReset.setFlat(True)
        self.btnReset.setObjectName("btnReset")
        self.gridLayout_12.addWidget(self.btnReset, 0, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_9)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelTotalDefect = QtWidgets.QLabel(self.frame_8)
        self.labelTotalDefect.setMinimumSize(QtCore.QSize(120, 30))
        self.labelTotalDefect.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelTotalDefect.setFont(font)
        self.labelTotalDefect.setAutoFillBackground(False)
        self.labelTotalDefect.setStyleSheet("image: url(:/images/res/back_ground.png);\n"
"color: rgb(255,255,255);")
        self.labelTotalDefect.setText("")
        self.labelTotalDefect.setTextFormat(QtCore.Qt.AutoText)
        self.labelTotalDefect.setPixmap(QtGui.QPixmap(":/images/res/back_ground.png"))
        self.labelTotalDefect.setScaledContents(False)
        self.labelTotalDefect.setWordWrap(False)
        self.labelTotalDefect.setObjectName("labelTotalDefect")
        self.horizontalLayout_5.addWidget(self.labelTotalDefect)
        self.labelTotalCell = QtWidgets.QLabel(self.frame_8)
        self.labelTotalCell.setMinimumSize(QtCore.QSize(120, 30))
        self.labelTotalCell.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelTotalCell.setFont(font)
        self.labelTotalCell.setStyleSheet("image: url(:/images/res/back_ground.png);\n"
"color: rgb(255,255,255);")
        self.labelTotalCell.setText("")
        self.labelTotalCell.setPixmap(QtGui.QPixmap(":/images/res/back_ground.png"))
        self.labelTotalCell.setObjectName("labelTotalCell")
        self.horizontalLayout_5.addWidget(self.labelTotalCell)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.gridLayout_17.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        self.frame_10.setStyleSheet("color: rgb(0, 0, 0);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_10.setLineWidth(1)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_8 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_13.addWidget(self.label_8, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)

        # self.calenFromDate = QtWidgets.QCalendarWidget(self.frame_10)
        # self.calenFromDate.setMinimumSize(QtCore.QSize(0, 25))
        # self.calenFromDate.setMaximumSize(QtCore.QSize(16777215, 25))
        # self.calenFromDate.setObjectName("calenFromDate")
        # self.horizontalLayout_6.addWidget(self.calenFromDate)

        self.fromdateEdit = QtWidgets.QDateEdit(QtCore.QDate.currentDate())
        # self.dateEdit.setMinimumDate(QtCore.QDate.currentDate().addDays(-365))
        # self.dateEdit.setMaximumDate(QtCore.QDate.currentDate().addDays(365))
        self.fromdateEdit.setDisplayFormat("yyyy.MM.dd")
        self.fromdateEdit.setObjectName("fromdateEdit")
        self.horizontalLayout_6.addWidget(self.fromdateEdit)

        self.fromTimeEdit = QtWidgets.QTimeEdit(QtCore.QTime.currentTime())
        # self.dateEdit.setMinimumDate(QtCore.QDate.currentDate().addDays(-365))
        # self.dateEdit.setMaximumDate(QtCore.QDate.currentDate().addDays(365))
        self.fromTimeEdit.setDisplayFormat("HH.mm.ss")
        self.fromdateEdit.setObjectName("fromTimeEdit")
        self.horizontalLayout_6.addWidget(self.fromTimeEdit)

        # self.coboFromTime = QtWidgets.QComboBox(self.frame_10)
        # self.coboFromTime.setMinimumSize(QtCore.QSize(0, 25))
        # self.coboFromTime.setMaximumSize(QtCore.QSize(16777215, 25))
        # self.coboFromTime.setObjectName("coboFromTime")
        # self.horizontalLayout_6.addWidget(self.coboFromTime)
        self.label_7 = QtWidgets.QLabel(self.frame_10)
        self.label_7.setMinimumSize(QtCore.QSize(30, 0))
        self.label_7.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)


        self.todateEdit = QtWidgets.QDateEdit(QtCore.QDate.currentDate())
        # self.dateEdit.setMinimumDate(QtCore.QDate.currentDate().addDays(-365))
        # self.dateEdit.setMaximumDate(QtCore.QDate.currentDate().addDays(365))
        self.todateEdit.setDisplayFormat("yyyy.MM.dd")
        self.todateEdit.setObjectName("todateEdit")
        self.horizontalLayout_6.addWidget(self.todateEdit)


        self.toTimeEdit = QtWidgets.QTimeEdit(QtCore.QTime.currentTime())
        # self.dateEdit.setMinimumDate(QtCore.QDate.currentDate().addDays(-365))
        # self.dateEdit.setMaximumDate(QtCore.QDate.currentDate().addDays(365))
        self.toTimeEdit.setDisplayFormat("HH.mm.ss")
        self.toTimeEdit.setObjectName("toTimeEdit")
        self.horizontalLayout_6.addWidget(self.toTimeEdit)


        # self.comboToDate = QtWidgets.QComboBox(self.frame_10)
        # self.comboToDate.setMinimumSize(QtCore.QSize(0, 25))
        # self.comboToDate.setMaximumSize(QtCore.QSize(16777215, 25))
        # self.comboToDate.setObjectName("comboToDate")
        # self.horizontalLayout_6.addWidget(self.comboToDate)
        # self.comboToTime = QtWidgets.QComboBox(self.frame_10)
        # self.comboToTime.setMinimumSize(QtCore.QSize(0, 25))
        # self.comboToTime.setMaximumSize(QtCore.QSize(16777215, 25))
        # self.comboToTime.setObjectName("comboToTime")
        # self.horizontalLayout_6.addWidget(self.comboToTime)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)

        self.btnpdfDownload = QtWidgets.QPushButton(self.frame_10)
        self.btnpdfDownload.setMinimumSize(QtCore.QSize(44, 53))
        self.btnpdfDownload.setMaximumSize(QtCore.QSize(44, 53))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        self.btnpdfDownload.setFont(font)
        # self.btnpdfDownload.setStyleSheet("image: url(:/images/res/back_ground.png);\n"
        #                                "color: rgb(255, 255, 255);")
        self.btnpdfDownload.setText("")
        # icon2 = QtGui.QIcon()
        # icon2.addPixmap(QtGui.QPixmap(":/images/res/back_ground.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.btnpdfDownload.setIcon(icon2)
        # self.btnpdfDownload.setIconSize(QtCore.QSize(120, 30))
        self.btnpdfDownload.setFlat(True)
        self.btnpdfDownload.setObjectName("btnpdfDownload")
        self.horizontalLayout_6.addWidget(self.btnpdfDownload)

        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)


        self.btnDownload = QtWidgets.QPushButton(self.frame_10)
        self.btnDownload.setMinimumSize(QtCore.QSize(44, 53))
        self.btnDownload.setMaximumSize(QtCore.QSize(44, 53))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        self.btnDownload.setFont(font)
        # self.btnDownload.setStyleSheet("image: url(:/images/res/back_ground.png);\n"
        # "color: rgb(255, 255, 255);")
        self.btnDownload.setText("")
        # icon2 = QtGui.QIcon()
        # icon2.addPixmap(QtGui.QPixmap(":/images/res/back_ground.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.btnDownload.setIcon(icon2)
        # self.btnDownload.setIconSize(QtCore.QSize(120, 30))
        self.btnDownload.setFlat(True)
        self.btnDownload.setObjectName("btnDownload")
        self.horizontalLayout_6.addWidget(self.btnDownload)

        spacerItem4 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)

        self.gridLayout_13.addLayout(self.horizontalLayout_6, 1, 0, -100, -100)
        self.gridLayout_17.addWidget(self.frame_10, 3, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frame_8, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.frame_7, 2, 1, 2, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setMinimumSize(QtCore.QSize(500, 350))
        self.frame_5.setMaximumSize(QtCore.QSize(500, 16777215))
        self.frame_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.labelWarning = QtWidgets.QLabel(self.frame_6)
        self.labelWarning.setMinimumSize(QtCore.QSize(200, 100))
        self.labelWarning.setMaximumSize(QtCore.QSize(200, 16777215))
        self.labelWarning.setStyleSheet("background-color: rgb(138, 138, 138);")
        self.labelWarning.setText("")
        self.labelWarning.setObjectName("labelWarning")
        self.horizontalLayout_3.addWidget(self.labelWarning)
        spacerItem4 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.gridLayout_10.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnCloseWarning = QtWidgets.QPushButton(self.frame_6)
        self.btnCloseWarning.setMinimumSize(QtCore.QSize(100, 30))
        self.btnCloseWarning.setMaximumSize(QtCore.QSize(100, 30))
        self.btnCloseWarning.setStyleSheet("color: rgb(0, 0, 0);")
        self.btnCloseWarning.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/res/close_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCloseWarning.setIcon(icon3)
        self.btnCloseWarning.setIconSize(QtCore.QSize(100, 30))
        self.btnCloseWarning.setFlat(True)
        self.btnCloseWarning.setObjectName("btnCloseWarning")
        self.horizontalLayout_2.addWidget(self.btnCloseWarning)
        self.gridLayout_10.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_6, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame_5)
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(2)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.Line1_3 = QtWidgets.QLabel(self.frame_3)
        self.Line1_3.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Line1_3.setFont(font)
        self.Line1_3.setStyleSheet("color: rgb(0, 0, 0);")
        self.Line1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Line1_3.setObjectName("Line1_3")
        self.gridLayout_7.addWidget(self.Line1_3, 0, 0, 1, 1)
        self.live2Detect = QtWidgets.QLabel(self.frame_3)
        self.live2Detect.setMinimumSize(QtCore.QSize(0, 225))
        self.live2Detect.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.live2Detect.setStyleSheet("background-color: rgb(168, 168, 168);")
        self.live2Detect.setText("")
        self.live2Detect.setObjectName("live2Detect")
        self.gridLayout_7.addWidget(self.live2Detect, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_7, 0, 1, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.Line1_4 = QtWidgets.QLabel(self.frame_3)
        self.Line1_4.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Line1_4.setFont(font)
        self.Line1_4.setStyleSheet("color: rgb(0, 0, 0);")
        self.Line1_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Line1_4.setObjectName("Line1_4")
        self.gridLayout_8.addWidget(self.Line1_4, 0, 0, 1, 1)
        self.live1Detect = QtWidgets.QLabel(self.frame_3)
        self.live1Detect.setMinimumSize(QtCore.QSize(0, 225))
        self.live1Detect.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.live1Detect.setStyleSheet("background-color: rgb(168, 168, 168);")
        self.live1Detect.setText("")
        self.live1Detect.setObjectName("live1Detect")
        self.gridLayout_8.addWidget(self.live1Detect, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_3, 1, 0, 1, 1)
        self.gridLayout_15.addWidget(self.frame_5, 3, 0, 1, 1)
        self.urlEdit = QtWidgets.QLabel(self.frame)
        self.urlEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.urlEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.urlEdit.setPalette(palette)
        self.urlEdit.setStyleSheet("background-color: rgb(161, 161, 161);\n"
"color: rgb(255, 255, 255);")
        self.urlEdit.setObjectName("urlEdit")
        self.gridLayout_15.addWidget(self.urlEdit, 1, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, -1, 5, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.openCameraBtn = QtWidgets.QPushButton(self.frame)
        self.openCameraBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.openCameraBtn.setMaximumSize(QtCore.QSize(30, 30))
        self.openCameraBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/res/camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openCameraBtn.setIcon(icon4)
        self.openCameraBtn.setIconSize(QtCore.QSize(20, 20))
        self.openCameraBtn.setFlat(True)
        self.openCameraBtn.setObjectName("openCameraBtn")
        self.horizontalLayout.addWidget(self.openCameraBtn)
        self.openVideoBtn = QtWidgets.QPushButton(self.frame)
        self.openVideoBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.openVideoBtn.setMaximumSize(QtCore.QSize(30, 30))
        self.openVideoBtn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/res/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openVideoBtn.setIcon(icon5)
        self.openVideoBtn.setIconSize(QtCore.QSize(20, 20))
        self.openVideoBtn.setFlat(True)
        self.openVideoBtn.setObjectName("openVideoBtn")
        self.horizontalLayout.addWidget(self.openVideoBtn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.rotateBtn = QtWidgets.QPushButton(self.frame)
        self.rotateBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.rotateBtn.setMaximumSize(QtCore.QSize(30, 30))
        self.rotateBtn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/res/rotate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rotateBtn.setIcon(icon6)
        self.rotateBtn.setIconSize(QtCore.QSize(20, 20))
        self.rotateBtn.setFlat(True)
        self.rotateBtn.setObjectName("rotateBtn")
        self.horizontalLayout.addWidget(self.rotateBtn)
        self.startBtn = QtWidgets.QPushButton(self.frame)
        self.startBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.startBtn.setMaximumSize(QtCore.QSize(30, 30))
        self.startBtn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/res/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startBtn.setIcon(icon7)
        self.startBtn.setIconSize(QtCore.QSize(20, 20))
        self.startBtn.setFlat(True)
        self.startBtn.setObjectName("startBtn")
        self.horizontalLayout.addWidget(self.startBtn)
        self.gridLayout_15.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.gridLayout_16.addWidget(self.frame, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.liveBtn = QtWidgets.QPushButton(DefectAnalytics)
        self.liveBtn.setMinimumSize(QtCore.QSize(150, 40))
        self.liveBtn.setMaximumSize(QtCore.QSize(150, 40))
        self.liveBtn.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/res/defect_btn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.liveBtn.setIcon(icon8)
        self.liveBtn.setIconSize(QtCore.QSize(150, 40))
        self.liveBtn.setFlat(True)
        self.liveBtn.setObjectName("liveBtn")
        self.horizontalLayout_4.addWidget(self.liveBtn)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.logoLabel = QtWidgets.QLabel(DefectAnalytics)
        self.logoLabel.setMinimumSize(QtCore.QSize(100, 30))
        self.logoLabel.setMaximumSize(QtCore.QSize(130, 30))
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap("res/label.png"))
        self.logoLabel.setObjectName("logoLabel")
        self.horizontalLayout_4.addWidget(self.logoLabel)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.minBtn = QtWidgets.QPushButton(DefectAnalytics)
        self.minBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.minBtn.setMaximumSize(QtCore.QSize(30, 30))
        self.minBtn.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/res/minimun.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minBtn.setIcon(icon9)
        self.minBtn.setIconSize(QtCore.QSize(20, 20))
        self.minBtn.setFlat(True)
        self.minBtn.setObjectName("minBtn")
        self.horizontalLayout_4.addWidget(self.minBtn)
        self.closeBtn = QtWidgets.QPushButton(DefectAnalytics)
        self.closeBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.closeBtn.setMaximumSize(QtCore.QSize(30, 30))
        self.closeBtn.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/res/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeBtn.setIcon(icon10)
        self.closeBtn.setIconSize(QtCore.QSize(20, 20))
        self.closeBtn.setFlat(True)
        self.closeBtn.setObjectName("closeBtn")
        self.horizontalLayout_4.addWidget(self.closeBtn)
        self.gridLayout_16.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)

        self.retranslateUi(DefectAnalytics)
        QtCore.QMetaObject.connectSlotsByName(DefectAnalytics)

    def retranslateUi(self, DefectAnalytics):
        _translate = QtCore.QCoreApplication.translate
        DefectAnalytics.setWindowTitle(_translate("DefectAnalytics", "DefectAnalytics"))
        self.label_2.setText(_translate("DefectAnalytics", "Live"))
        self.Line1_2.setText(_translate("DefectAnalytics", "Line2"))
        self.Line1.setText(_translate("DefectAnalytics", "Line1"))
        self.label_4.setText(_translate("DefectAnalytics", "Defects Analytics"))
        item = self.defectTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DefectAnalytics", "SN"))
        item = self.defectTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DefectAnalytics", "Defect Name"))
        item = self.defectTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DefectAnalytics", "Conveyer Belt"))
        item = self.defectTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("DefectAnalytics", "DateTime"))
        item = self.defectTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("DefectAnalytics", "Defect Snapshot"))
        self.label_8.setText(_translate("DefectAnalytics", "Download Report"))
        self.label_7.setText(_translate("DefectAnalytics", "--"))
        self.label_3.setText(_translate("DefectAnalytics", "Defects Identified"))
        self.Line1_3.setText(_translate("DefectAnalytics", "Last detected Defect - Line2"))
        self.Line1_4.setText(_translate("DefectAnalytics", "Last detected Defect - Line1"))
        self.urlEdit.setText(_translate("DefectAnalytics", "Cam1"))
from pyqtgraph import PlotWidget
